[package]
name = "postscript"
version = "0.12.2"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides a parser for PostScript fonts."
documentation = "https://docs.rs/postscript"
homepage = "https://github.com/bodoni/postscript"
repository = "https://github.com/bodoni/postscript"
categories = ["parsing"]
keywords = ["font", "postscript", "typeface", "typography"]
exclude = ["tests/fixtures/*"]

[dev-dependencies]
random = "0.12"

[[bench]]
name = "postscript"
path = "benches/lib.rs"

[[test]]
name = "postscript"
path = "tests/lib.rs"
